# Generated by Django 3.2.19 on 2024-03-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('编号', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('产地名称', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': '产地',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('编号', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('名称', models.CharField(blank=True, max_length=20, null=True)),
                ('备注', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '科室资料',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('编号', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('姓名', models.CharField(max_length=20)),
                ('性别', models.CharField(blank=True, max_length=2, null=True)),
                ('科室', models.CharField(blank=True, max_length=20, null=True)),
                ('备注', models.CharField(blank=True, max_length=50, null=True)),
                ('出生日期', models.DateTimeField(blank=True, null=True)),
                ('入职日期', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '医生资料',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drug_classification',
            fields=[
                ('编号', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('名称', models.CharField(blank=True, max_length=50, null=True)),
                ('备注', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '药品分类',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drug_information',
            fields=[
                ('编号', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('名称', models.CharField(max_length=50)),
                ('规格', models.CharField(blank=True, max_length=50, null=True)),
                ('整量单位', models.CharField(blank=True, max_length=50, null=True)),
                ('散量单位', models.CharField(blank=True, max_length=50, null=True)),
                ('入库单价', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('出库单价', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('批发价', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('整散比', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('分类', models.CharField(blank=True, max_length=50, null=True)),
                ('费用归类', models.CharField(blank=True, max_length=50, null=True)),
                ('拼音码', models.CharField(blank=True, max_length=50, null=True)),
                ('效期', models.CharField(blank=True, max_length=20, null=True)),
                ('上限', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('下限', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': '药品资料',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drug_inventory',
            fields=[
                ('库存编号', models.AutoField(primary_key=True, serialize=False)),
                ('库房', models.CharField(blank=True, max_length=50, null=True)),
                ('药品编号', models.CharField(max_length=20)),
                ('药品数量', models.DecimalField(decimal_places=2, max_digits=12)),
                ('备注', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '药品库存',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fee_items',
            fields=[
                ('编号', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('名称', models.CharField(max_length=100)),
                ('拼音码', models.CharField(blank=True, max_length=20, null=True)),
                ('费用', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('费用分类', models.CharField(blank=True, max_length=50, null=True)),
                ('病种分类', models.CharField(blank=True, max_length=50, null=True)),
                ('备注', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '门诊收费项目',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outpatient_details',
            fields=[
                ('编号', models.SmallAutoField(primary_key=True, serialize=False)),
                ('划价编号', models.CharField(max_length=15)),
                ('药品编号', models.CharField(max_length=20)),
                ('单价', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('数量', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('金额', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': '门诊划价明细',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outpatient_pricing',
            fields=[
                ('编号', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('科室', models.CharField(blank=True, max_length=30, null=True)),
                ('挂号编号', models.CharField(blank=True, max_length=15, null=True)),
                ('医生', models.CharField(blank=True, max_length=10, null=True)),
                ('划价时间', models.DateTimeField(blank=True, null=True)),
                ('划价员', models.CharField(blank=True, max_length=10, null=True)),
                ('是否收费', models.CharField(blank=True, max_length=2, null=True)),
                ('收费员', models.CharField(blank=True, max_length=10, null=True)),
                ('收费时间', models.DateTimeField(blank=True, null=True)),
                ('划价金额', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('是否发药', models.CharField(blank=True, max_length=2, null=True)),
                ('发药时间', models.DateTimeField(blank=True, null=True)),
                ('发药员', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': '门诊划价',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outpatient_registration',
            fields=[
                ('编号', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('病人编号', models.CharField(blank=True, max_length=15, null=True)),
                ('姓名', models.CharField(blank=True, max_length=30, null=True)),
                ('性别', models.CharField(blank=True, max_length=2, null=True)),
                ('挂号科室', models.CharField(blank=True, max_length=30, null=True)),
                ('费用类型', models.CharField(blank=True, max_length=30, null=True)),
                ('挂号类型', models.CharField(blank=True, max_length=30, null=True)),
                ('挂号费用', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('医生', models.CharField(blank=True, max_length=30, null=True)),
                ('时间', models.DateTimeField(blank=True, null=True)),
                ('是否已划价', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': '门诊挂号',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('编号', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('姓名', models.CharField(blank=True, max_length=30, null=True)),
                ('性别', models.CharField(blank=True, max_length=4, null=True)),
                ('年龄', models.IntegerField(blank=True, null=True)),
                ('民族', models.CharField(blank=True, max_length=20, null=True)),
                ('费用类型', models.CharField(blank=True, max_length=20, null=True)),
                ('电话', models.CharField(blank=True, max_length=15, null=True)),
                ('拼音码', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': '病人信息库',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('编号', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('名称', models.CharField(blank=True, max_length=20, null=True)),
                ('备注', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '职务资料',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registration_type',
            fields=[
                ('编号', models.IntegerField(primary_key=True, serialize=False)),
                ('挂号类型', models.CharField(blank=True, max_length=20, null=True)),
                ('挂号费', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': '门诊挂号类型',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('编号', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('名称', models.CharField(blank=True, max_length=20, null=True)),
                ('备注', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '计量单位',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('账号', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('密码', models.CharField(max_length=255)),
                ('权限', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '用户管理',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('编号', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('名称', models.CharField(blank=True, max_length=50, null=True)),
                ('位置', models.CharField(blank=True, max_length=100, null=True)),
                ('备注', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '库房资料',
                'managed': False,
            },
        ),
    ]
